// Fill out your copyright notice in the Description page of Project Settings.


#include "UI/APITest/APITestOverlay.h"
#include "UI/APITest/APITestManager.h"
#include "UI/API/ListFleets/ListFleetsBox.h"
#include "Components/Button.h"
#include "Components/ScrollBox.h"
#include "UI/HTTP/HTTPRequestTypes.h"
#include "UI/API/ListFleets/FleetId.h"
#include "Components/TextBlock.h"

void UAPITestOverlay::NativeConstruct()
{
	Super::NativeConstruct(); 

	check(APITestManagerClass); 
	APITestManager = NewObject<UAPITestManager>(this, APITestManagerClass); 

	check(ListFleetsBox); 
	check(ListFleetsBox->Button_ListFleets)
	ListFleetsBox->Button_ListFleets->OnClicked.AddDynamic(this, &UAPITestOverlay::ListFleetsButtonClicked); 
}

void UAPITestOverlay::ListFleetsButtonClicked()
{
	check(APITestManagerClass); 
	APITestManager->OnListFleetsResponseReceived.AddDynamic(this, &UAPITestOverlay::OnListFleetsResponseReceived); 
	APITestManager->ListFleets(); 
	ListFleetsBox->Button_ListFleets->SetIsEnabled(false); 
}

void UAPITestOverlay::OnListFleetsResponseReceived(const FDSListFleetsResponse& ListFleetsResponse, bool bWasSuccessful)
{
	if (APITestManager->OnListFleetsResponseReceived.IsAlreadyBound(this, &UAPITestOverlay::OnListFleetsResponseReceived))
	{
		APITestManager->OnListFleetsResponseReceived.RemoveDynamic(this, &UAPITestOverlay::OnListFleetsResponseReceived); 
	}
	ListFleetsBox->ScrollBox_ListFleets->ClearChildren(); 
	if (bWasSuccessful)
	{
		for (const FString& FleetId : ListFleetsResponse.FleetIds)
		{
			UFleetId* FleetIdWidget = CreateWidget<UFleetId>(this, FleetIdWidgetClass); 
			FleetIdWidget->TextBlock_FleetId->SetText(FText::FromString(FleetId)); 
			ListFleetsBox->ScrollBox_ListFleets->AddChild(FleetIdWidget); 
		}
	}
	else
	{
		UFleetId* FleetIdWidget = CreateWidget<UFleetId>(this, FleetIdWidgetClass);
		FleetIdWidget->TextBlock_FleetId->SetText(FText::FromString("Something went wrong!"));
		ListFleetsBox->ScrollBox_ListFleets->AddChild(FleetIdWidget);
	}
	ListFleetsBox->Button_ListFleets->SetIsEnabled(true); 
}
